### ISSUE TITLE
Wrong execution time in production

### ISSUE THREAD

**Issue by BoShurik** [yiisoft/demo#137]
Without `Builder::rebuild();` on every request `Timer` instance cached with [initial value](https://github.com/yiisoft/yii-demo/blob/master/config/common.php#L26) so time in the footer shows time elapsed from the config rebuild but not the request time

**Comment by samdark** [comment]
Yeah. That could be removed :) There's no a debugger that already collects data well.

**Comment by samdark** [comment]
There's no another way to build configs so that no longer applies.
