### ISSUE TITLE
Help needed to start. Not a bug report or something like that.

### ISSUE THREAD

**Issue by ArtMin96** [yiisoft/demo#305]
I'm trying to switch from yii2 to yii3. Is there any documentation or materials to use? As a new user, I'm so confused. I do not find anything to study.

**Comment by vjik** [comment]
See [Upgrading from Version 2.0](https://github.com/yiisoft/docs/blob/master/guide/en/intro/upgrade-from-v2.md)

Please note that Yii 3 is version in development and not yet released.
