### ISSUE TITLE
Do not see exception messages in console

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/demo#332]
Is any instruction how to set .env variable.
Probably thus I do not see any exception messages in console.
https://github.com/yiisoft/demo/blob/991551df1d761eb5370eb2e28a0717de3edd89ba/yii#L12

**Comment by samdark** [comment]
> Is any instruction how to set .env variable.

```bash
env=test ./yii
```

**Comment by andrew-svirin** [comment]
Thank you
