### ISSUE TITLE
No definition or class found or resolvable for App\Blog\Post\PostController

### ISSUE THREAD

**Issue by raszek** [yiisoft/demo#348]
### What steps will reproduce the problem?
1. Create user
2. Login
3. Go to blog
4. Click "Add post"
### What is the expected result?
Page with form
### What do you get instead?
Error:

Yiisoft\Definitions\Exception\NotFoundException
No definition or class found or resolvable for App\Blog\Post\PostController.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.0.1
| Operating system | Windows 10

**Comment by samdark** [comment]
Fixed.
