### ISSUE TITLE
Temporary error handler wrong log dir

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/demo#375]
Good day. In `WebApplicationRunner::createTemporaryErrorHandler` class `FileTarget` take first argument as `dirname(__DIR__) . '/runtime/logs/app.log'. But it's create **/runtime/logs/app.log** in **src** directory extends of **@root/runtime**. Thanks

**Comment by rustamwin** [comment]
This issue seems to be fixed in `yiisoft/yii-runner-http`.
