### ISSUE TITLE
Add default Dependency Injections for controllers, BaseController or some other solution implementation

### ISSUE THREAD

**Issue by miqoo1996** [yiisoft/demo#411]
Hi there,

I'm excited to see that Yii3 comes to real use, I especially like that you've used DI and meantime I have some suggestions :) 

All your controllers have bunch of classes injected via __constructor(), actually that looks great on one hand but on another hand it makes you to do the code duplication for every controller you're going to have. Of course, developer can always make an abstract BaseContoller and keep the injections there, I agree with that, if you could keep the abstract class in your framwework by default that would be great because not every developer can figure out what's going on there, especially the junior developers who are quite newbie in PHP. 

Thanks

public function __construct(ResponseFactoryInterface $responseFactory, UrlGeneratorInterface $urlGenerator, ...)
{
    $this->responseFactory = $responseFactory;
    $this->urlGenerator = $urlGenerator;
    ....
}

**Comment by miqoo1996** [comment]
To my understating, we can have something like this, the classes are taken from Yii3 default container. 

```php
abstract class BaseControllerContainer
{
    private function initDefaultDi()
    {
        $this->logger = YourYii3Container::$mapp['logger'];
        $this->cache = YourYii3Container::$mapp['cache'];
    }

    public function __construct()
    {
        $this->initDefaultDi();
    }
}

abstract class BaseController extends BaseControllerContainer
{

}

final class PostController extends BaseController
{
    private CacheInterface $cache;

    public function __construct(CacheInterface $cache)
    {
        parent::__construct($cache);
        $this->cache = $cache;
    }
}
```

**Comment by miqoo1996** [comment]
For example in Yii2 we could take the session from Yii::$app->session, that's great idea if it the class have contumely usage in project.

**Comment by samdark** [comment]
That's both good for typing and very bad for explicitness of dependencies and static analysis capabilities. When developing Yii3 we were focusing on the latter.

Having a container globally and staticall available makes it essentially a service locator that might be considered as a handy anti-pattern. The consequence of using it is that you're strictly binding your classes to depend on `YourYii3Container` rather than real dependencies so at least in tests you'll have to initialize this container instead of testing what should really be tested.

**Comment by miqoo1996** [comment]
Then it could be like the below example:

```php

class YiiTools
{
    private CacheInterface $cache;
    private LoggerInterface $logger;
    private SessionInterface $session;
    private ViewInterface $session;
    ....

    public function __construct(CacheInterface $cache, LoggerInterface $logger, SessionInterface $session, ...)
    {
        $this->cache = $cache;
        $this->logger = $logger;
        $this->session = $session;
    }
}

final class PostController
{
    private YiiTools $yiiTools;

    public function __construct(YiiTools $yiiTools)
    {
        $this->yiiTools = $yiiTools;
    }
    
    public function blog()
    {
        $this->session->put('test', 'test session');
        
        return $this->view->render(...);
    }
}

```

I think this won't be affecting the tests.

**Comment by samdark** [comment]
That still has half of the drawbacks: it's very implicit. I'm against of having it at this point.
