### ISSUE TITLE
./yii fixture/add console command not working

### ISSUE THREAD

**Issue by arogachev** [yiisoft/demo#439]
According Codeception test fails as well.

### What steps will reproduce the problem?

Run `./yii fixture/add` console command`.

### What is the expected result?

No errors.

### What do you get instead?

```
./yii fixture/add
                                                                                                                        
 [ERROR] Transaction can't be finished. Some relations can't be resolved:                                               
Create new `postTag`                                                                                           
- tag.posts:postTag (Cycle\ORM\Relation\ShadowBelongsTo)  
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | current master
| PHP version      | https://github.com/yiisoft/demo/blob/3d6ca817d4efd08a4acf1a3a93521422c5764421/docker-compose.yml#L5
| Operating system | https://github.com/yiisoft/demo/blob/3d6ca817d4efd08a4acf1a3a93521422c5764421/docker-compose.yml#L5

**Comment by rossaddison** [comment]
Encountering a similar issue with all my BelongsTo relations: 

Cycle\ORM\Exception\TransactionException: Transaction can't be finished. Some relations can't be resolved:
Update `product`
 - family (Cycle\ORM\Relation\BelongsTo) in C:\wamp64\www\yii-invoice\vendor\cycle\orm\src\Exception\TransactionException.php:40
Stack trace:
#0 C:\wamp64\www\yii-invoice\vendor\cycle\orm\src\Transaction\UnitOfWork.php(104): Cycle\ORM\Exception\TransactionException::unresolvedRelations(Array, Object(Cycle\ORM\Service\Implementation\RelationProvider))
#1 C:\wamp64\www\yii-invoice\vendor\cycle\orm\src\Transaction.php(48): Cycle\ORM\Transaction\UnitOfWork->run()
#2 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-cycle\src\Data\Writer\EntityWriter.php(30): Cycle\ORM\Transaction->run()
#3 C:\wamp64\www\yii-invoice\src\Invoice\Product\ProductRepository.php(59): Yiisoft\Yii\Cycle\Data\Writer\EntityWriter->write(Array)
#4 C:\wamp64\www\yii-invoice\src\Invoice\Product\ProductService.php(30): App\Invoice\Product\ProductRepository->save(Object(App\Invoice\Entity\Product Cycle ORM Proxy))
#5 C:\wamp64\www\yii-invoice\src\Invoice\Product\ProductController.php(239): App\Invoice\Product\ProductService->saveProduct(Object(App\Invoice\Entity\Product Cycle ORM Proxy), Object(App\Invoice\Product\ProductForm))
#6 [internal function]: App\Invoice\Product\ProductController->edit(Object(Yiisoft\Yii\View\ViewRenderer), Object(HttpSoft\Message\ServerRequest), Object(Yiisoft\Router\CurrentRoute), Object(Yiisoft\Validator\Validator), Object(App\Invoice\Product\ProductRepository), Object(App\Invoice\Setting\SettingRepository), Object(App\Invoice\Family\FamilyRepository), Object(App\Invoice\Unit\UnitRepository), Object(App\Invoice\TaxRate\TaxRateRepository), Object(App\Handler\NotFoundHandler))
#7 C:\wamp64\www\yii-invoice\vendor\yiisoft\injector\src\Injector.php(66): ReflectionFunction->invokeArgs(Array)
#8 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareFactory.php(89): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#9 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#10 C:\wamp64\www\yii-invoice\vendor\yiisoft\auth\src\Middleware\Authentication.php(57): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#11 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Auth\Middleware\Authentication->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#12 C:\wamp64\www\yii-invoice\src\Middleware\AccessChecker.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#13 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareFactory.php(126): App\Middleware\AccessChecker->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#14 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#15 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-debug-viewer\src\Middleware\ToolbarMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#16 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Yii\Debug\Viewer\Middleware\ToolbarMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#17 C:\wamp64\www\yii-invoice\vendor\yiisoft\data-response\src\Middleware\FormatDataResponse.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#18 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#19 C:\wamp64\www\yii-invoice\vendor\yiisoft\csrf\src\CsrfMiddleware.php(48): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#20 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Csrf\CsrfMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#21 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#22 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(50): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#23 C:\wamp64\www\yii-invoice\vendor\yiisoft\router\src\MatchingResult.php(116): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#24 C:\wamp64\www\yii-invoice\vendor\yiisoft\router\src\Middleware\Router.php(61): Yiisoft\Router\MatchingResult->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#25 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Router\Middleware\Router->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#26 C:\wamp64\www\yii-invoice\src\Middleware\LocaleMiddleware.php(94): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#27 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): App\Middleware\LocaleMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#28 C:\wamp64\www\yii-invoice\vendor\yiisoft\user\src\Login\Cookie\CookieLoginMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#29 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\User\Login\Cookie\CookieLoginMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#30 C:\wamp64\www\yii-invoice\vendor\yiisoft\cookies\src\CookieMiddleware.php(84): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#31 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#32 C:\wamp64\www\yii-invoice\vendor\yiisoft\session\src\SessionMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#33 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#34 C:\wamp64\www\yii-invoice\vendor\yiisoft\error-handler\src\Middleware\ErrorCatcher.php(135): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#35 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(104): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#36 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#37 C:\wamp64\www\yii-invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(50): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#38 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-http\src\Application.php(87): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#39 C:\wamp64\www\yii-invoice\vendor\yiisoft\yii-runner-http\src\HttpApplicationRunner.php(103): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#40 C:\wamp64\www\yii-invoice\public\index.php(36): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#41 {main}

**Comment by rossaddison** [comment]
Similar to Albertborsos' issue, the relations work when adding and then submitting but not when editing and then submitting; using the same form of course.

**Comment by vjik** [comment]
All tests pass after https://github.com/yiisoft/demo/pull/454
