### ISSUE TITLE
 Codeception test fails (SignupAcceptanceCest: Test register success)

### ISSUE THREAD

**Issue by arogachev** [yiisoft/demo#441]
### What steps will reproduce the problem?

```
./vendor/bin/codecept run
```

### What is the expected result?

No errors.

### What do you get instead?

```
Test register success
 Test  tests/Acceptance/SignupAcceptanceCest.php:testRegisterSuccess
 Step  See "Hello, everyone!"
 Fail  Failed asserting that  on page /signup
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | current master
| PHP version      | https://github.com/yiisoft/demo/blob/3d6ca817d4efd08a4acf1a3a93521422c5764421/docker-compose.yml#L5
| Operating system | https://github.com/yiisoft/demo/blob/3d6ca817d4efd08a4acf1a3a93521422c5764421/docker-compose.yml#L5

**Comment by vjik** [comment]
All tests pass after https://github.com/yiisoft/demo/pull/454
