### ISSUE TITLE
Composer Install/Update when Init

### ISSUE THREAD

**Issue by chanurholis** [yiisoft/demo#457]
### What steps will reproduce the problem?
1. git clone project
2. composer install/update

### What is the expected result?
success

### What do you get instead?
![image](https://user-images.githubusercontent.com/55186337/172435371-76b57767-358c-49e9-a4e4-264cb705268a.png)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0
| PHP version      | PHP 8.1.6
| Operating system | Linux (Xubuntu 21.10)

**Comment by chanurholis** [comment]
help

**Comment by samdark** [comment]
Thanks for reporting but it looks like your local networking problem. I've just did `composer install` without any issues.

**Comment by chanurholis** [comment]
How I can solved this issue? @samdark

**Comment by samdark** [comment]
No idea. VPN maybe?
