### ISSUE TITLE
yii serve require php 8.1

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/demo#474]
``` ./yii.bat serve```

```
In Command.php line 360:                                      
  syntax error, unexpected token ")"  
```

In \Symfony\Component\Console\Command\Command
![image](https://user-images.githubusercontent.com/874234/179306522-306ccff3-2399-4b46-a5c2-dd93a12a3ed2.png)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.0.24
| Operating system | Win11

**Comment by samdark** [comment]
I guess it could be fixed by adding LTS of https://github.com/yiisoft/demo/blob/master/composer.json#L36
