### ISSUE TITLE
Dummy mysql date ie. '0000-00-00' is presented as -0001-11-30 in Cycle in a View

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#509]
### What steps will reproduce the problem?  Presenting a DateTimeImmutable as a string in a view using: 
eg.  ($client->getClient_birthdate())->format($datehelper->style())

### Additional info

| Q                | A
| ---------------- | ---
| mySql version          | 8.0.27
| PHP version      |  8.1.9
| Operating system | Windows 10

**Comment by xepozz** [comment]
What does `$datehelper->style()` provide?

**Comment by rossaddison** [comment]
The $datehelper->style() provides the mysql format ie. 'Y-m-d'

**Comment by rossaddison** [comment]
I have managed to resolve the problem with the following code. Perhaps you can suggest something better.

I am using the below code to present this date as a dummy date in the view or even as an empty string.
eg. 
(($client->getClient_birthdate())->format($datehelper->style()))  === '-0001-11-30' ? '0000-00-00' 
                                                                                                                                       : 
(($client->getClient_birthdate())->format($datehelper->style()))

**Comment by rossaddison** [comment]
I dont know why Cycle returns the '-0001-11-30'. Is this a dummy date in cycle as well? There is nothing in the documentation and nothing in their issues as well.

**Comment by xepozz** [comment]
What time inside `getClient_birthdate()`? Could you dump it with `var_dump()` and show the result?

**Comment by rossaddison** [comment]
Ok just var_dumped it and it presents the current date ie. 2022-10-01 so I will therefore present the string as the current date.
Thanks I had not thought of var_dumping the date. Mainly use var_dumping for array complexity. Cool. Problem solved. Thanks for the quick response.

**Comment by rossaddison** [comment]
Oops closed it a little too early.

**Comment by rossaddison** [comment]
I am going to leave this topic open.  I am going to present the date as '0000-00-00' for the time being.

**Comment by xepozz** [comment]
What's value of that cell in db?
I think you store `-0001-11-30 00:00:00.000000` in the db and that's why PHP shows you that string.

**Comment by rossaddison** [comment]
The value of the cell is '0000-00-00'. I have read the following in mySql documentation:
````
[5.1.11 Server SQL Modes](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html)
https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html
With strict mode disabled, invalid dates such as '2004-04-31' are converted to '0000-00-00' and a warning is generated. NO_ZERO_DATE The NO_ZERO_DATE mode affects whether the server permits '0000-00-00' as a valid date. If this mode is not enabled, ... The MySQL server can operate in different SQL modes, and can apply these modes differently for different clients, depending on the value of the sql_mode system ...
[B.3.4.2 Problems Using DATE Columns](https://dev.mysql.com/doc/refman/8.0/en/using-date.html)
https://dev.mysql.com/doc/refman/8.0/en/using-date.html
The special “zero” date '0000-00-00' can be stored and retrieved as '0000-00-00'. When a '0000-00-00' date is used through Connector/ODBC, it is automatically converted to NULL because ODBC cannot handle that kind of date. MySQL permits you to ...You should use this format in UPDATE expressions and in the WHERE clause of SELECT ...

````

**Comment by rossaddison** [comment]
I get this if I go into the wampserver menu. 
![image](https://user-images.githubusercontent.com/8538339/193446188-eaf28f9a-15d2-4a14-8966-ee4b3ed97504.png)

**Comment by rossaddison** [comment]
I am currently in user mode so I see all these values and am using mySql version 8.0.27:

NO_ZERO_DATE, NO_ZERO_IN_DATE, NO_AUTO_CREATE_USER

**Comment by rossaddison** [comment]
This is an interesting article: [https://tableplus.com/blog/2019/10/incorrect-date-value-0000-00-00-date-datetime.html](url)

**Comment by rossaddison** [comment]
So I am NOT running in strict mode and therefore the mySql is allowing these '0000-00-00' dates. 

I think the solution to avoid this issue completely is simply to set the default date for unfilled dates to: 

(new \DateTimeImmutable('now'))->format('Y-m-d').

This will ensure that the current date is at least in the mySql field and this will avoid the '0000-00-00' issue.

**Comment by rossaddison** [comment]
The above solution works but I will leave this open for discussion.

**Comment by xepozz** [comment]
@roxblnfk do you know how to solve it in Cycle?

**Comment by rossaddison** [comment]
If you can point me in the right direction I would appreciate it.

**Comment by rossaddison** [comment]
[I have raised an issue here](https://github.com/cycle/orm/issues/364)

**Comment by samdark** [comment]
Closing since it's not issue of the Yii framework itself.
