### ISSUE TITLE
TypeError Cannot assign Cycle\ORM\Reference\Reference to property App\Invoice\Entity\Quote::$client of type ?App\Invoice\Entity\Client

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#510]
### What steps will reproduce the problem?  In src\Invoice\Entity\Quote.php
````
class Quote
{    
    #[BelongsTo(target:Client::class, nullable: false, fkAction:'NO ACTION')]     <----- changing the nullable: true to false
    public ?Client $client = null;    

    #[BelongsTo(target:Group::class, nullable: false, fkAction:'NO ACTION')]     <----- changing the nullable: true to false
    private ?Group $group = null;
````

### What do you get instead? The above error.
TypeError
`Cannot assign Cycle\ORM\Reference\Reference to property App\Invoice\Entity\Quote::$client of type ?App\Invoice\Entity\Client`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | mySql  8.0.27
| PHP version      |  8.1.9
| Operating system | Windows 10

**Comment by rossaddison** [comment]
The problem has been resolved by simply changing the nullable: false to true.  The Invoice entity, which is very similar to the Quote entity however has its nullable: set to true for the very same foreign keys and is running without this error. So this is confusing. Is it related to the  schema perhaps?

**Comment by roxblnfk** [comment]
Which mapper do you use?

**Comment by roxblnfk** [comment]
There are no enough code to reproduce or to understand the issue in description.

**Comment by roxblnfk** [comment]
I think the exception has been thrown because an Entity class has been used directly instead of EntityProxy. But why i see ProxyEntityFactory in the stack in this case?

**Comment by rossaddison** [comment]
Here is the config/params: 
```
 'orm-promise-factory' => null,
        //'orm-promise-factory' => \Cycle\ORM\Promise\ProxyFactory::class, 
        /**
         * A list of DB schema providers for {@see \Yiisoft\Yii\Cycle\Schema\Provider\Support\SchemaProviderPipeline}
         * Providers are implementing {@see SchemaProviderInterface}.
         * The configuration is an array of provider class names. Alternatively, you can specify provider class as key
         * and its config as value:
         */
```

**Comment by rossaddison** [comment]
This issue has been solved. Typo public should be private.  

public ?Client $client = null;       <-------- change public to private.
