### ISSUE TITLE
Psalm Level 6: 3 of 9: InvalidReturnStatement - src/Command/Fixture/AddCommand.php:73:20 - The inferred type 'int|non-falsy-string' does not match the declared return type 'int' for App\Command\Fixture\AddCommand::execute (see https://psalm.dev/128)             return $t->getCode() ?: ExitCode::UNSPECIFIED_ERROR;

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#530]
<?xml version="1.0"?>
<psalm
    errorLevel="6"        <------------------------------------------------------- change level 7 to 6
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <file name="public/index.php"/>
        <file name="yii"/>
        <file name="autoload.php"/>
    </projectFiles>
</psalm>

**Comment by vjik** [comment]
Closed favor in https://github.com/yiisoft/demo/issues/538
