### ISSUE TITLE
Psalm Level 6: 6 of 9: InvalidReturnType - src/User/Console/CreateCommand.php:36:81 - The declared return type 'int' for App\User\Console\CreateCommand::execute is incorrect, got 'int|non-falsy-string' (see https://psalm.dev/011)     protected function execute(InputInterface $input, OutputInterface $output): int

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#533]
<?xml version="1.0"?>
<psalm
    errorLevel="6"        <------------------------------------------------------- change level 7 to 6
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <file name="public/index.php"/>
        <file name="yii"/>
        <file name="autoload.php"/>
    </projectFiles>
</psalm>

**Comment by vjik** [comment]
Closed favor in https://github.com/yiisoft/demo/issues/538
