### ISSUE TITLE
Minor Issue: Dependency Checker - The following 6 unknown symbols were found

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#539]
After posting a commit the dependency checker is giving the following: 

![image](https://user-images.githubusercontent.com/8538339/200134400-4767c77a-62de-4750-80ab-e1f76b314572.png)

How can I correct this?

**Comment by vjik** [comment]
Need add composer dependencies:
- `yiisoft/arrays`
- `yiisoft/files`
- `yiisoft/json`
- `yiisoft/yii-runner`

And, seems, make lowercase `Date` function [here](https://github.com/yiisoft/demo/blob/23647cd21cefb4ea6f7af69ccbe65fff499b0a5c/resources/views/blog/archive/index.php#L55).

**Comment by rossaddison** [comment]
Thanks Vjik. I will definitely try that.

**Comment by rossaddison** [comment]
Ok 👌. Just a small observation not related to this issue. 

The blog index appears as follows: 
![image](https://user-images.githubusercontent.com/8538339/200138334-0ec92dff-4188-43db-a076-a8087cb7402a.png)

**Comment by vjik** [comment]
@rossaddison It's OK for me:

![image](https://user-images.githubusercontent.com/525501/200156254-d7cda255-6713-4d52-9eef-2be2c08d00cd.png)

Try update demo.

**Comment by rossaddison** [comment]
Included the following at the end of composer.json:

        "yiisoft/arrays": "*",
        "yiisoft/files": "*",
        "yiisoft/json": "*",
        "yiisoft/yii-runner": "*"

Blog index solved itself.

Thanks for your help.
