### ISSUE TITLE
Yiisoft\Di\NotFoundException No definition or class found or resolvable for "Yiisoft\Validator\RuleHandlerContainer" while building "Yiisoft\Validator\RuleHandlerContainer".

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#554]
### Additional info

| Q                | A
| ---------------- | ---
| PHP version      |  8.1.12
 Operating system | Windows 10

Here is the stack trace.

Yiisoft\Di\NotFoundException: No definition or class found or resolvable for "Yiisoft\Validator\RuleHandlerContainer" while building "Yiisoft\Validator\RuleHandlerContainer". in C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php:517
Stack trace:
#0 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(481): Yiisoft\Di\Container->buildInternal('Yiisoft\\Validat...')
#1 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(135): Yiisoft\Di\Container->build('Yiisoft\\Validat...')
#2 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\Reference.php(67): Yiisoft\Di\Container->get('Yiisoft\\Validat...')
#3 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(514): Yiisoft\Definitions\Reference->resolve(Object(Yiisoft\Di\Container))
#4 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(481): Yiisoft\Di\Container->buildInternal('Yiisoft\\Validat...')
#5 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(135): Yiisoft\Di\Container->build('Yiisoft\\Validat...')
#6 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\ParameterDefinition.php(75): Yiisoft\Di\Container->get('Yiisoft\\Validat...')
#7 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\Helpers\DefinitionResolver.php(65): Yiisoft\Definitions\ParameterDefinition->resolve(Object(Yiisoft\Di\Container))
#8 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\Helpers\DefinitionResolver.php(44): Yiisoft\Definitions\Helpers\DefinitionResolver::resolve(Object(Yiisoft\Di\Container), NULL, Object(Yiisoft\Definitions\ParameterDefinition))
#9 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\ArrayDefinition.php(237): Yiisoft\Definitions\Helpers\DefinitionResolver::resolveArray(Object(Yiisoft\Di\Container), NULL, Array)
#10 C:\wamp64\www\yii-invoice8\vendor\yiisoft\definitions\src\ArrayDefinition.php(142): Yiisoft\Definitions\ArrayDefinition->resolveFunctionArguments(Object(Yiisoft\Di\Container), Array, Array)
#11 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(514): Yiisoft\Definitions\ArrayDefinition->resolve(Object(Yiisoft\Di\Container))
#12 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(481): Yiisoft\Di\Container->buildInternal('Yiisoft\\Validat...')
#13 C:\wamp64\www\yii-invoice8\vendor\yiisoft\di\src\Container.php(135): Yiisoft\Di\Container->build('Yiisoft\\Validat...')
#14 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(309): Yiisoft\Di\Container->get('Yiisoft\\Validat...')
#15 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(290): Yiisoft\Injector\Injector->resolveObjectParameter(Object(Yiisoft\Injector\ResolvingState), 'Yiisoft\\Validat...', false)
#16 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(255): Yiisoft\Injector\Injector->resolveNamedType(Object(Yiisoft\Injector\ResolvingState), Object(ReflectionNamedType), false)
#17 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(195): Yiisoft\Injector\Injector->resolveParameterType(Object(Yiisoft\Injector\ResolvingState), Object(ReflectionNamedType), false, NULL)
#18 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(154): Yiisoft\Injector\Injector->resolveParameter(Object(ReflectionParameter), Object(Yiisoft\Injector\ResolvingState))
#19 C:\wamp64\www\yii-invoice8\vendor\yiisoft\injector\src\Injector.php(68): Yiisoft\Injector\Injector->resolveDependencies(Object(ReflectionFunction), Array)
#20 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\WrapperFactory.php(81): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#21 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#22 C:\wamp64\www\yii-invoice8\vendor\yiisoft\rate-limiter\src\LimitRequestsMiddleware.php(44): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#23 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\RateLimiter\LimitRequestsMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#24 C:\wamp64\www\yii-invoice8\vendor\yiisoft\yii-debug-viewer\src\Middleware\ToolbarMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#25 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Viewer\Middleware\ToolbarMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#26 C:\wamp64\www\yii-invoice8\vendor\yiisoft\data-response\src\Middleware\FormatDataResponse.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#27 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#28 C:\wamp64\www\yii-invoice8\vendor\yiisoft\csrf\src\CsrfMiddleware.php(48): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#29 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Csrf\CsrfMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#30 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#31 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#32 C:\wamp64\www\yii-invoice8\vendor\yiisoft\router\src\MatchingResult.php(112): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#33 C:\wamp64\www\yii-invoice8\vendor\yiisoft\router\src\Middleware\Router.php(59): Yiisoft\Router\MatchingResult->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#34 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Router\Middleware\Router->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#35 C:\wamp64\www\yii-invoice8\vendor\yiisoft\yii-middleware\src\Locale.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#36 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Middleware\Locale->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#37 C:\wamp64\www\yii-invoice8\vendor\yiisoft\user\src\Login\Cookie\CookieLoginMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#38 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\User\Login\Cookie\CookieLoginMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#39 C:\wamp64\www\yii-invoice8\vendor\yiisoft\cookies\src\CookieMiddleware.php(84): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#40 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#41 C:\wamp64\www\yii-invoice8\vendor\yiisoft\session\src\SessionMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#42 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#43 C:\wamp64\www\yii-invoice8\vendor\yiisoft\yii-sentry\src\SentryMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#44 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Sentry\SentryMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#45 C:\wamp64\www\yii-invoice8\vendor\yiisoft\error-handler\src\Middleware\ErrorCatcher.php(135): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#46 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#47 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#48 C:\wamp64\www\yii-invoice8\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#49 C:\wamp64\www\yii-invoice8\vendor\yiisoft\yii-http\src\Application.php(77): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#50 C:\wamp64\www\yii-invoice8\vendor\yiisoft\yii-runner-http\src\HttpApplicationRunner.php(103): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#51 C:\wamp64\www\yii-invoice8\public\index.php(35): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#52 {main}

**Comment by vjik** [comment]
Make sure that you pull last changes. In [PR](https://github.com/yiisoft/demo/pull/553) we adapt demo applications to last changes in validator.
