### ISSUE TITLE
could some body release a zip file with the installed vendor folder?

### ISSUE THREAD

**Issue by wudimei** [yiisoft/demo#558]
### What steps will reproduce the problem?
composer install
### What is the expected result?
successfully install
### What do you get instead?
could some body release a zip file with the installed vendor folder?

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.1
| Operating system | win10

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/form dev-master requires yiisoft/html ^3.0 -> found yiisoft/html[3.0.0] but it conflicts with your root composer.json require (^2.4).
    - yiisoft/form 1.0.x-dev is an alias of yiisoft/form dev-master and thus requires it to be installed too.
    - Root composer.json requires yiisoft/form ^1.0@dev -> satisfiable by yiisoft/form[1.0.x-dev (alias of dev-master)].

**Comment by rossaddison** [comment]
Tried?
"yiisoft/html": "^3.0", <--- upgrade 2.4 to 3
"yiisoft/mailer": "^5.0", <---- upgrade 4 to 5
"yiisoft/mailer-symfony": "dev-master",
"yiisoft/view": "^7.0", <--- upgrade 6 to 7
