### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by Fluit** [yiisoft/demo#567]
### What steps will reproduce the problem?
error when using composer install 

### What do you get instead?
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii-bootstrap5 dev-master requires yiisoft/widget ^2.0 -> found yiisoft/widget[2.0.0] but it conflicts with your root composer.json require (^1.1).
    - yiisoft/yii-bootstrap5 3.0.x-dev is an alias of yiisoft/yii-bootstrap5 dev-master and thus requires it to be installed too.
    - Root composer.json requires yiisoft/yii-bootstrap5 ^3.0@dev -> satisfiable by yiisoft/yii-bootstrap5[3.0.x-dev (alias of dev-master)].

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.
| PHP version      | 8.1
| Operating system | Windows

**Comment by rustamwin** [comment]
Will be fixed after merging #566.
