### ISSUE TITLE
PHP Fatal Error — Yiisoft\ErrorHandler\Exception\ErrorException Class App\Widget\FlashMessage contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Yiisoft\Widget\Widget::render)

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#568]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by rossaddison** [comment]
To avoid the above error I have changed the 'final' to 'abstract' since class Widget contains an abstract method.

**Comment by rustamwin** [comment]
Fixed in https://github.com/yiisoft/demo/pull/566

**Comment by rossaddison** [comment]
Working fine now. Replaced 3 files. Thanks
