### ISSUE TITLE
Move language groups to params, configure translator

### ISSUE THREAD

**Issue by samdark** [yiisoft/demo#588]
Both https://github.com/yiisoft/demo/blob/master/blog/config/common/di/router.php#L22 and
https://github.com/yiisoft/demo/blob/master/blog-api/config/common/di/router.php#L23
 should be fixed the same way as https://github.com/yiisoft/app/commit/c4dde1808a725e27c6c20eec3a92d1b2e29468e2

**Comment by vjik** [comment]
Fixed by https://github.com/yiisoft/demo/pull/599
