### ISSUE TITLE
Bad URI prefix — Yiisoft\Yii\Middleware\Exception\BadUriPrefixException

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/demo#596]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by rossaddison** [comment]
I have manually added a /blog to the browser url and this calls up the index page.  I suspect this is a .htaccess issue as I have tried to edit the baseUrl parameter in the config/params.php without success.

**Comment by rossaddison** [comment]
````
if (!str_starts_with($path, $baseUrl)) {
                throw new BadUriPrefixException('URI prefix doesn\'t match.');
            }
````

Substituting the $path and the $baseUrl parameters in the throw's string yields:
````
$path = '/'        (path is the haystack)
$baseUrl = '/blog'   (baseUrl is the needle)
 ````
So the needle is definitely not in the haystack.

So the path clearly needs to be built up to '/blog' or the baseUrl needs to be reduced to / for them both to match.

The error message says ' Make sure that path from the web address contains the specified prefix'. 
Substituting $this->prefix in the throw's message gives '/blog'.

So the path clearly needs to be built upto '/blog'. So where can we add '/blog' to the prefix?

**Comment by xepozz** [comment]
Try to set `YII_ENV=/`, but in `.env`, not `.env.example` file
https://github.com/yiisoft/demo/blob/master/blog/.env.example#L1

**Comment by rossaddison** [comment]
This is working: 

![image](https://github.com/yiisoft/demo/assets/8538339/a4596b3a-699f-442d-8c1c-ca276c20696e)

with .env

````
YII_ENV=
YII_DEBUG=true
SENTRY_DSN=
BASE_URL=
````

The BASE_URL had /blog in it which I removed.  

Thanks!
