### ISSUE TITLE
Duplicate key "yiisoft/yii-view-renderer => viewPath" in the following configs while building "params-web" group

### ISSUE THREAD

**Issue by ahmadasjad** [yiisoft/demo#621]
### What steps will reproduce the problem?
latest demo app, version provided below

### What is the expected result?
It shouldn't give any duplicate key error.
I went through the config docs here: https://github.com/yiisoft/config
Found similar issue https://github.com/yiisoft/config/issues/20. But as it's expected behaviour, it should be managed by root app. I tried adding these two inside `vendor-override-layer` config, but no luck

### What do you get instead?
Duplicate key "yiisoft/yii-view-renderer => viewPath" in the following configs while building "params-web" group:
- vendor/yiisoft/yii-view-renderer/config/params.php
- vendor/yiisoft/yii-view/config/params.php

### Additional info

| Q                | A
| ---------------- | ---
| Version          | master: 6dbcb105bb495b764413c19ea17bfd6e6136acdb
| PHP version      | PHP 8.3.3
| Operating system | Linux 69d607727b8b 6.5.11-linuxkit # 1 SMP PREEMPT_DYNAMIC Wed Dec  6 17:14:50 UTC 2023 x86_64 GNU/Linux

Stacktrace:
```
ErrorException: Duplicate key "yiisoft/yii-view-renderer => viewPath" in the following configs while building "params-web" group:
 - vendor/yiisoft/yii-view-renderer/config/params.php
 - vendor/yiisoft/yii-view/config/params.php in /app/vendor/yiisoft/config/src/Merger.php:272
Stack trace:
#0 /app/vendor/yiisoft/config/src/Merger.php(146): Yiisoft\Config\Merger->throwDuplicateKeyErrorException('params-web', Array, Array)
#1 /app/vendor/yiisoft/config/src/Merger.php(123): Yiisoft\Config\Merger->performMerge(Object(Yiisoft\Config\Context), Array, Array, Array, NULL, false, 1)
#2 /app/vendor/yiisoft/config/src/Merger.php(65): Yiisoft\Config\Merger->performMerge(Object(Yiisoft\Config\Context), Array, Array, Array, NULL, false)
#3 /app/vendor/yiisoft/config/src/Config.php(111): Yiisoft\Config\Merger->merge(Object(Yiisoft\Config\Context), Array, Array)
#4 /app/vendor/yiisoft/config/src/Config.php(109): Yiisoft\Config\Config->buildGroup('params', Array, 'params-web')
#5 /app/vendor/yiisoft/config/src/Config.php(92): Yiisoft\Config\Config->buildGroup('params-web')
#6 /app/vendor/yiisoft/config/src/Config.php(72): Yiisoft\Config\Config->runBuildParams()
#7 /app/vendor/yiisoft/yii-runner/src/ApplicationRunner.php(156): Yiisoft\Config\Config->get('di-web')
#8 /app/vendor/yiisoft/yii-runner/src/ApplicationRunner.php(189): Yiisoft\Yii\Runner\ApplicationRunner->getConfiguration('di-web')
#9 /app/vendor/yiisoft/yii-runner/src/ApplicationRunner.php(144): Yiisoft\Yii\Runner\ApplicationRunner->createDefaultContainer()
#10 /app/vendor/yiisoft/yii-runner-http/src/HttpApplicationRunner.php(131): Yiisoft\Yii\Runner\ApplicationRunner->getContainer()
#11 /app/public/index.php(40): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#12 {main}
```

**Comment by vjik** [comment]
`yiisoft/yii-view-renderer` is new name for `yiisoft/yii-view` package. Just remove `yiisoft/yii-view` from your app.
